tools: unset BUNDLE_GEMFILE and better structure.

diff --git a/tools/ci-build b/tools/ci-build
--- a/tools/ci-build
+++ b/tools/ci-build
@@ -24,20 +24,26 @@ license() {
     return 0
 }
 
-rspec_ok=0
-license_ok=0
+main() {
+    rspec_ok=0
+    license_ok=0
 
-if ! rspec; then
-    rspec_ok=1
-fi
+    if ! rspec; then
+        rspec_ok=1
+    fi
 
-if ! license; then
-    license_ok=1
-fi
+    if ! license; then
+        license_ok=1
+    fi
 
-if [[ $rspec_ok -ne 0 || $license_ok -ne 0 ]]; then
-    echo "Build resulted in failures!" >&2
-    exit 1
-fi
+    if [[ $rspec_ok -ne 0 || $license_ok -ne 0 ]]; then
+        echo "Build resulted in failures!" >&2
+        return 0
+    fi
 
-exit 0
+    return 1
+}
+
+unset BUNDLE_GEMFILE
+main
+exit $?
diff --git a/tools/ci-rspec-all b/tools/ci-rspec-all
--- a/tools/ci-rspec-all
+++ b/tools/ci-rspec-all
@@ -1,37 +1,37 @@
 #!/bin/bash
 
-bundle=$PWD/vendor/bundle
-exit_status=0
+main() {
+    bundle_path=$PWD/vendor/bundle
+    status=0
 
-bundle install --path $bundle
+    while read -u 3 gemfile; do
+        dir=$(dirname $gemfile)
 
-if ! bundle exec rspec; then
-    exit_status=1
-fi
+        if [[ ! -d $dir/spec ]]; then
+            continue
+        fi
 
-while read -u 3 gemfile; do
-    dir=$(dirname $gemfile)
+        echo "Running specs in: $dir"
 
-    if [[ ! -d $dir/spec ]]; then
-        continue
+        (
+            cd $dir
+            bundle install --path $bundle_path
+
+            if ! bundle exec rspec; then
+                status=1
+            fi
+        )
+    done 3< <(find -name vendor -prune -o -type f -name Gemfile -print)
+
+    if [[ $status -eq 0 ]]; then
+        echo "Tests SUCCESSFUL!"
+    else
+        echo "Tests FAILED!" >&2
     fi
 
-    echo "Running specs in: $dir"
+    return $status
+}
 
-    (
-        cd $dir
-        bundle install --path $bundle
-
-        if ! bundle exec rspec; then
-            exit_status=1
-        fi
-    )
-done 3< <(find plugins -name Gemfile)
-
-if [[ $exit_status -eq 0 ]]; then
-    echo "Tests SUCCESSFUL!"
-else
-    echo "Tests FAILED!" >&2
-fi
-
-exit $exit_status
+unset BUNDLE_GEMFILE
+main
+exit $?
